import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  canAutoGenerateDoubleEliminationRounds,
  countDoubleElimGamesMax,
  countDoubleElimGamesMin,
  district6TenUParticipantSlots,
  generateDoubleEliminationRoundsForFormat,
  generateDoubleEliminationRoundsFromTeams,
} from "@/lib/tournament-brackets/generateDoubleElimFromTeams";
import { littleLeagueSixTeamParticipantSlots } from "@/lib/tournament-brackets/littleLeagueParticipantShells";

function allMatches(rounds: ReturnType<typeof generateDoubleEliminationRoundsFromTeams>) {
  return rounds.flatMap((r) => r.matches);
}

function gameNumbers(rounds: ReturnType<typeof generateDoubleEliminationRoundsFromTeams>) {
  return allMatches(rounds)
    .map((m) => m.officialGameNumber)
    .filter(Boolean)
    .map(Number)
    .sort((a, b) => a - b);
}

describe("generateDoubleElimFromTeams", () => {
  it("supports power-of-2 auto sizes 4 through 32", () => {
    for (const n of [4, 8, 16, 32]) {
      const teams = Array.from({ length: n }, (_, i) => `Team ${i + 1}`);
      assert.equal(canAutoGenerateDoubleEliminationRounds(teams, "double_elimination"), true);
      assert.equal(canAutoGenerateDoubleEliminationRounds(teams, "modified_double_elimination"), true);
    }
  });

  it("modified double elimination omits if-necessary championship game", () => {
    const rounds = generateDoubleEliminationRoundsForFormat(["A", "B", "C", "D"], "modified_double_elimination");
    const championship = rounds.filter((r) => r.bracketSection === "championship");
    assert.equal(championship.length, 1);
    assert.equal(championship[0]!.label, "Championship");
    assert.equal(championship[0]!.matches.length, 1);
    assert.equal(championship[0]!.matches[0]!.championshipRole, "grand_final");
    assert.deepEqual(gameNumbers(rounds), [1, 2, 3, 4, 5, 6]);
  });

  it("generates 4-team bracket with 7 games and correct feeders", () => {
    const rounds = generateDoubleEliminationRoundsFromTeams(["A", "B", "C", "D"]);
    const nums = gameNumbers(rounds);
    assert.deepEqual(nums, [1, 2, 3, 4, 5, 6, 7]);
    assert.equal(countDoubleElimGamesMin(4), 6);
    assert.equal(countDoubleElimGamesMax(4), 7);

    const winners = rounds.filter((r) => r.bracketSection === "winners");
    const losers = rounds.filter((r) => r.bracketSection === "losers");
    const championship = rounds.filter((r) => r.bracketSection === "championship");
    assert.equal(winners.length, 2);
    assert.equal(losers.length, 2);
    assert.equal(championship.length, 1);

    assert.equal(winners[0]!.matches[0]!.home, "A");
    assert.equal(winners[0]!.matches[0]!.away, "D");
    assert.equal(winners[0]!.matches[1]!.home, "B");
    assert.equal(winners[0]!.matches[1]!.away, "C");
    assert.equal(winners[1]!.matches[0]!.home, "W1");
    assert.equal(winners[1]!.matches[0]!.away, "W2");

    assert.equal(losers[0]!.matches[0]!.home, "L1");
    assert.equal(losers[0]!.matches[0]!.away, "L2");
    assert.equal(losers[1]!.matches[0]!.home, "W4");
    assert.equal(losers[1]!.matches[0]!.away, "L3");

    const champ = championship[0]!.matches;
    assert.equal(champ[0]!.home, "W3");
    assert.equal(champ[0]!.away, "W5");
    assert.equal(champ[0]!.championshipRole, "grand_final");
    assert.equal(champ[1]!.home, "W6");
    assert.equal(champ[1]!.away, "L6");
    assert.equal(champ[1]!.championshipRole, "if_necessary");
  });

  it("generates 8-team bracket with 15 games and correct championship feeders", () => {
    const teams = ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8"];
    const rounds = generateDoubleEliminationRoundsFromTeams(teams);
    const nums = gameNumbers(rounds);
    assert.equal(nums.length, 15);
    assert.equal(nums[0], 1);
    assert.equal(nums[nums.length - 1], 15);
    assert.equal(countDoubleElimGamesMin(8), 14);
    assert.equal(countDoubleElimGamesMax(8), 15);

    const winners = rounds.filter((r) => r.bracketSection === "winners");
    const losers = rounds.filter((r) => r.bracketSection === "losers");
    assert.equal(winners.length, 3);
    assert.equal(winners[0]!.matches.length, 4);
    assert.equal(winners[1]!.matches.length, 2);
    assert.equal(winners[2]!.matches.length, 1);

    const lbMatches = losers.flatMap((r) => r.matches);
    assert.equal(lbMatches.length, 6);
    assert.equal(lbMatches[0]!.home, "L1");
    assert.equal(lbMatches[0]!.away, "L2");
    assert.equal(lbMatches[4]!.home, "W10");
    assert.equal(lbMatches[4]!.away, "W11");
    assert.equal(lbMatches[5]!.home, "W12");
    assert.equal(lbMatches[5]!.away, "L7");

    const champ = rounds.find((r) => r.bracketSection === "championship")!.matches;
    assert.equal(champ[0]!.officialGameNumber, "14");
    assert.equal(champ[0]!.home, "W7");
    assert.equal(champ[0]!.away, "W13");
    assert.equal(champ[1]!.officialGameNumber, "15");
    assert.equal(champ[1]!.home, "W14");
    assert.equal(champ[1]!.away, "L14");
  });

  it("pads non-power-of-two team counts with BYE slots", () => {
    const rounds = generateDoubleEliminationRoundsFromTeams(["A", "B", "C", "D", "E", "F"]);
    const wbR1 = rounds.find((r) => r.bracketSection === "winners")!.matches;
    assert.equal(wbR1.length, 4);
    const byeSlots = wbR1.flatMap((m) => [m.home, m.away]).filter((s) => s === "BYE");
    assert.equal(byeSlots.length, 2);
  });

  it("pads 5 teams to 8 slots with standard top-seed byes when no custom slots", () => {
    const teams = ["Ponchatoula", "Loranger", "Kentwood", "Franklinton", "Gonzales"];
    const rounds = generateDoubleEliminationRoundsFromTeams(teams);
    const wbR1 = rounds.find((r) => r.bracketSection === "winners")!.matches;
    assert.equal(wbR1.length, 4);
    const liveR1 = wbR1.filter((m) => m.officialGameNumber);
    assert.equal(wbR1[0]!.home, "Ponchatoula");
    assert.equal(wbR1[0]!.away, "BYE");
    assert.equal(wbR1[1]!.home, "Franklinton");
    assert.equal(wbR1[1]!.away, "Gonzales");
    assert.equal(liveR1.length, 1);
    assert.equal(liveR1[0]!.officialGameNumber, "1");
    const champ = rounds.find((r) => r.bracketSection === "championship")!.matches;
    assert.equal(champ.length, 2);
    assert.equal(champ[0]!.championshipRole, "grand_final");
    assert.equal(champ[1]!.championshipRole, "if_necessary");
  });

  it("District 6 10U uses fixed slots: G1/G2 openers and G3 W1 vs Gonzales", () => {
    const teams = ["Ponchatoula", "Loranger", "Kentwood", "Franklinton", "Gonzales"];
    const rounds = generateDoubleEliminationRoundsFromTeams(teams, {
      participantSlots: district6TenUParticipantSlots(),
    });
    const nums = gameNumbers(rounds);
    assert.ok(nums.length < 15);
    const wb = rounds.filter((r) => r.bracketSection === "winners").flatMap((r) => r.matches);
    const g1 = wb.find((m) => m.officialGameNumber === "1");
    const g2 = wb.find((m) => m.officialGameNumber === "2");
    const g3 = wb.find((m) => m.officialGameNumber === "3");
    assert.equal(g1!.home, "Ponchatoula");
    assert.equal(g1!.away, "Loranger");
    assert.equal(g2!.home, "Kentwood");
    assert.equal(g2!.away, "Franklinton");
    assert.equal(g3!.home, "W1");
    assert.equal(g3!.away, "Gonzales");
    const lb = rounds.filter((r) => r.bracketSection === "losers").flatMap((r) => r.matches);
    const g4 = lb.find((m) => m.officialGameNumber === "4");
    const g6 = lb.find((m) => m.officialGameNumber === "6");
    const g7 = lb.find((m) => m.officialGameNumber === "7");
    const champ = rounds.find((r) => r.bracketSection === "championship")!.matches[0]!;
    assert.equal(g4!.home, "L1");
    assert.equal(g4!.away, "L2");
    assert.equal(g6!.home, "W4");
    assert.equal(g6!.away, "L3");
    assert.ok(g7);
    assert.equal(g7!.home, "L4");
    assert.equal(g7!.away, "W6");
    assert.equal(champ.home, "W5");
    assert.equal(champ.away, "W7");
    assert.equal(wb.filter((m) => !m.officialGameNumber).length >= 2, true);
  });

  it("Little League 6-team shell: two R1 games and W1/E, W2/F semis", () => {
    const teams = ["A", "B", "C", "D", "E", "F"];
    const rounds = generateDoubleEliminationRoundsFromTeams(teams, {
      participantSlots: littleLeagueSixTeamParticipantSlots(teams),
      includeIfNecessaryGame: false,
    });
    const wb = rounds.filter((r) => r.bracketSection === "winners").flatMap((r) => r.matches);
    const g1 = wb.find((m) => m.officialGameNumber === "1");
    const g2 = wb.find((m) => m.officialGameNumber === "2");
    const g3 = wb.find((m) => m.officialGameNumber === "3");
    const g4 = wb.find((m) => m.officialGameNumber === "4");
    assert.equal(g1!.home, "A");
    assert.equal(g1!.away, "B");
    assert.equal(g2!.home, "C");
    assert.equal(g2!.away, "D");
    assert.equal(g3!.home, "W1");
    assert.equal(g3!.away, "E");
    assert.equal(g4!.home, "W2");
    assert.equal(g4!.away, "F");
    const liveR1 = wb.filter((m) => m.officialGameNumber === "1" || m.officialGameNumber === "2");
    assert.equal(liveR1.length, 2);
  });
});
