"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import BracketTeamPicker from "@/components/admin/BracketTeamPicker";
import type { BracketSpec } from "@/lib/tournament-brackets/bracketSpec";
import {
  BYE_SLOT_LABEL,
  canAutoGenerateSingleEliminationRounds,
  countByesForTeamList,
  generateSingleEliminationRoundsFromTeams,
  nextPowerOfTwoAtLeast,
} from "@/lib/tournament-brackets/generateSingleElimFromTeams";
import {
  canAutoGenerateDoubleEliminationRounds,
  countByesForDoubleElimTeamList,
  countDoubleElimGamesMax,
  countDoubleElimGamesMin,
  generateDoubleEliminationRoundsForFormat,
} from "@/lib/tournament-brackets/generateDoubleElimFromTeams";
import {
  isDoubleEliminationFormat,
  bracketFormatForChampionshipSeriesStyle,
  resolveChampionshipSeriesStyle,
  type ChampionshipSeriesStyle,
} from "@/lib/tournament-brackets/bracketFormat";
import {
  classicDoubleElimLayoutLockPatch,
  officialTemplateLayoutLockPatch,
  CLASSIC_DOUBLE_ELIM_LAYOUT_LOCKED_ADMIN_MESSAGE,
  isClassicDoubleElimLayoutLocked,
  resolveDoubleElimClassicLayoutGenerationOptions,
} from "@/lib/tournament-brackets/doubleEliminationClassicLayoutTemplate";
import {
  buildRoundsFromOfficialTemplate,
  defaultOfficialTemplateForNewProject,
  getOfficialTemplate,
  listOfficialTemplates,
  officialTemplateChampionshipLabel,
  type OfficialTemplateId,
} from "@/lib/tournament-brackets/officialTemplates";

type BracketFormat = BracketSpec["bracketFormat"];
type SetupMode = "official" | "custom";

type Step = "format" | "division" | "champion" | "teams" | "byes" | "confirm" | "non_single_done";

type Props = {
  spec: BracketSpec;
  projectId: string;
  organizationId: string;
  seasonYear: number;
  busy: boolean;
  /** When true, bracket structure + preview are visible; wizard can be collapsed or reopened to adjust answers. */
  setupComplete: boolean;
  onApply: (patch: Record<string, unknown>) => Promise<void>;
  /** Unlocks structure/preview without generating rounds (empty or imported projects). */
  onSkipGuidedSetup: () => Promise<void>;
};

export default function BracketSetupWizard({
  spec,
  projectId,
  organizationId,
  seasonYear,
  busy,
  setupComplete,
  onApply,
  onSkipGuidedSetup,
}: Props) {
  const [showWizardSession, setShowWizardSession] = useState(false);
  const [step, setStep] = useState<Step>("format");
  const defaultTemplate = defaultOfficialTemplateForNewProject();
  const [setupMode, setSetupMode] = useState<SetupMode>("official");
  const [officialTemplateId, setOfficialTemplateId] = useState<OfficialTemplateId>(defaultTemplate.id);
  const [championshipSeriesStyle, setChampionshipSeriesStyle] = useState<ChampionshipSeriesStyle>(
    defaultTemplate.defaultChampionshipSeriesStyle,
  );
  const [bracketFormat, setBracketFormat] = useState<BracketFormat>("modified_double_elimination");
  const [divisionLabel, setDivisionLabel] = useState("");
  const [championAgeGroupDraft, setChampionAgeGroupDraft] = useState("");
  const [includeThirdPlaceDraft, setIncludeThirdPlaceDraft] = useState(false);
  const [teams, setTeams] = useState<string[]>([]);
  const [rosterAgeGroupDraft, setRosterAgeGroupDraft] = useState("");
  const [byeAck, setByeAck] = useState(false);

  const seedFromSpec = useCallback(() => {
    if (spec.officialTemplateId && getOfficialTemplate(spec.officialTemplateId)) {
      setSetupMode("official");
      setOfficialTemplateId(spec.officialTemplateId as OfficialTemplateId);
      const style = resolveChampionshipSeriesStyle(spec) ?? defaultTemplate.defaultChampionshipSeriesStyle;
      setChampionshipSeriesStyle(style);
      setBracketFormat(bracketFormatForChampionshipSeriesStyle(style));
    } else if (spec.bracketFormat === "unknown") {
      setSetupMode("official");
      setOfficialTemplateId(defaultTemplate.id);
      setChampionshipSeriesStyle(defaultTemplate.defaultChampionshipSeriesStyle);
      setBracketFormat("modified_double_elimination");
    } else {
      setSetupMode("custom");
      setBracketFormat(spec.bracketFormat);
      const style = resolveChampionshipSeriesStyle(spec);
      if (style) setChampionshipSeriesStyle(style);
    }
    setDivisionLabel(spec.divisionLabel ?? "");
    setChampionAgeGroupDraft(spec.championAgeGroupLabel?.trim() || spec.divisionLabel?.trim() || "");
    setIncludeThirdPlaceDraft(Boolean(spec.singleElimIncludeThirdPlace));
    setTeams(spec.teams.length > 0 ? spec.teams.filter(Boolean) : defaultTemplate.teamCount ? Array.from({ length: defaultTemplate.teamCount }, (_, i) => String.fromCharCode(65 + i)) : []);
    setRosterAgeGroupDraft(spec.rosterAgeGroup?.trim() ?? "");
    setByeAck(false);
    setStep("format");
  }, [
    defaultTemplate,
    spec,
  ]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      seedFromSpec();
      setShowWizardSession(false);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [projectId, seedFromSpec]);

  useEffect(() => {
    if (!setupComplete && spec.pdfIngestHints) {
      const timer = window.setTimeout(() => {
        setShowWizardSession(true);
      }, 0);
      return () => window.clearTimeout(timer);
    }
    return undefined;
  }, [projectId, setupComplete, spec.pdfIngestHints]);

  const teamsText = useMemo(() => teams.join("\n"), [teams]);
  const liveTeamCount = useMemo(() => teams.map((t) => t.trim()).filter(Boolean).length, [teams]);
  const activeOfficialTemplate = useMemo(
    () => (setupMode === "official" ? getOfficialTemplate(officialTemplateId) : undefined),
    [officialTemplateId, setupMode],
  );
  const officialTemplateOptions = useMemo(() => listOfficialTemplates("little_league"), []);
  const byeCount = useMemo(() => {
    if (activeOfficialTemplate && activeOfficialTemplate.teamCount <= 6) return 0;
    if (isDoubleEliminationFormat(bracketFormat)) return countByesForDoubleElimTeamList(teams);
    return countByesForTeamList(teams);
  }, [activeOfficialTemplate, bracketFormat, teams]);
  const slotN = useMemo(() => (teams.length >= 1 ? nextPowerOfTwoAtLeast(teams.length) : 0), [teams.length]);
  const canBuildSingle = useMemo(
    () => canAutoGenerateSingleEliminationRounds(teams, "single_elimination"),
    [teams],
  );
  const canBuildDouble = useMemo(() => {
    if (activeOfficialTemplate) return liveTeamCount === activeOfficialTemplate.teamCount;
    return isDoubleEliminationFormat(bracketFormat) && canAutoGenerateDoubleEliminationRounds(teams, bracketFormat);
  }, [activeOfficialTemplate, bracketFormat, liveTeamCount, teams]);
  const canBuild =
    setupMode === "official"
      ? canBuildDouble
      : bracketFormat === "single_elimination"
        ? canBuildSingle
        : isDoubleEliminationFormat(bracketFormat)
          ? canBuildDouble
          : false;

  const previewRounds = useMemo(() => {
    if (teams.length < 1) return null;
    try {
      if (activeOfficialTemplate && canBuildDouble) {
        return buildRoundsFromOfficialTemplate(activeOfficialTemplate.id, teams, {
          championshipSeriesStyle,
        });
      }
      if (isDoubleEliminationFormat(bracketFormat) && canBuildDouble) {
        return generateDoubleEliminationRoundsForFormat(teams, bracketFormat, {
          ...resolveDoubleElimClassicLayoutGenerationOptions(teams, bracketFormat),
          championshipSeriesStyle,
        });
      }
      if (bracketFormat === "single_elimination" && canBuildSingle) {
        return generateSingleEliminationRoundsFromTeams(teams);
      }
      return null;
    } catch {
      return null;
    }
  }, [activeOfficialTemplate, bracketFormat, canBuildDouble, canBuildSingle, championshipSeriesStyle, teams]);

  const showFullWizard = !setupComplete || showWizardSession;

  function openUpdateAnswers() {
    seedFromSpec();
    setShowWizardSession(true);
  }

  async function applySingleElim() {
    if (!previewRounds) return;
    const label = divisionLabel.trim();
    await onApply({
      bracketFormat: "single_elimination",
      divisionLabel: label.length > 0 ? label : "",
      championAgeGroupLabel: championAgeGroupDraft.trim() || null,
      rosterAgeGroup: rosterAgeGroupDraft.trim() || null,
      singleElimIncludeThirdPlace: includeThirdPlaceDraft,
      teams,
      rounds: previewRounds,
      setupWizardCompleted: true,
    });
    setShowWizardSession(false);
  }

  async function applyDoubleElimBuild() {
    if (!previewRounds) return;
    if (setupMode !== "official" && !isDoubleEliminationFormat(bracketFormat)) return;
    const label = divisionLabel.trim();
    const syncedFormat = bracketFormatForChampionshipSeriesStyle(championshipSeriesStyle);
    await onApply({
      bracketFormat: syncedFormat,
      officialTemplateId: activeOfficialTemplate?.id ?? null,
      layoutPreference: activeOfficialTemplate ? "official" : "connected_columns",
      governingBody: activeOfficialTemplate?.governingBody ?? null,
      divisionLabel: label.length > 0 ? label : "",
      championAgeGroupLabel: championAgeGroupDraft.trim() || null,
      rosterAgeGroup: rosterAgeGroupDraft.trim() || null,
      championshipSeriesStyle,
      teams,
      rounds: previewRounds,
      setupWizardCompleted: true,
      ...classicDoubleElimLayoutLockPatch(teams, syncedFormat),
      ...officialTemplateLayoutLockPatch(activeOfficialTemplate?.id),
    });
    setShowWizardSession(false);
  }

  async function applyNonSingle() {
    const label = divisionLabel.trim();
    await onApply({
      bracketFormat,
      divisionLabel: label.length > 0 ? label : "",
      setupWizardCompleted: true,
    });
    setShowWizardSession(false);
  }

  function goNextFromFormat() {
    if (setupMode === "official" || bracketFormat === "single_elimination" || isDoubleEliminationFormat(bracketFormat)) {
      if (setupMode === "official") {
        setBracketFormat(bracketFormatForChampionshipSeriesStyle(championshipSeriesStyle));
      }
      setStep("division");
    } else {
      setStep("non_single_done");
    }
  }

  function goNextFromTeams() {
    if (teams.length < 1) return;
    if (!canBuild) return;
    if (byeCount > 0) {
      setByeAck(false);
      setStep("byes");
    } else {
      setStep("confirm");
    }
  }

  function goNextFromByes() {
    if (byeCount > 0 && !byeAck) return;
    setStep("confirm");
  }

  if (!showFullWizard && setupComplete) {
    const layoutLocked = isClassicDoubleElimLayoutLocked(spec);
    return (
      <div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-zinc-400">Guided bracket setup</h2>
        <p className="mt-1 text-xs text-zinc-500">
          {layoutLocked
            ? CLASSIC_DOUBLE_ELIM_LAYOUT_LOCKED_ADMIN_MESSAGE
            : "Questionnaire finished. Bracket structure and preview are available below. Open again if you need to change answers and rebuild."}
        </p>
        {layoutLocked ? null : (
          <button
            type="button"
            disabled={busy}
            className="mt-3 rounded-lg border border-violet-700/60 bg-violet-950/40 px-3 py-2 text-xs font-semibold text-violet-100 hover:bg-violet-900/50 disabled:opacity-40"
            onClick={() => openUpdateAnswers()}
          >
            Review or change answers
          </button>
        )}
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-violet-900/40 bg-violet-950/15 p-4">
      <div className="flex flex-wrap items-start justify-between gap-2">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-violet-300">Guided bracket setup</h2>
        {setupComplete ? (
          <button
            type="button"
            disabled={busy}
            className="text-xs text-zinc-500 hover:text-zinc-300"
            onClick={() => setShowWizardSession(false)}
          >
            Close
          </button>
        ) : null}
      </div>

      {!setupComplete ? (
        <p className="mt-2 text-xs text-zinc-500">
          Answer each step, confirm on the last screen, then use <strong className="text-zinc-400">Build bracket</strong>{" "}
          to unlock Bracket structure and Preview for this project.
        </p>
      ) : null}

      {spec.pdfIngestHints ? (
        <p className="mt-2 rounded-lg border border-emerald-900/50 bg-emerald-950/30 px-3 py-2 text-xs text-emerald-100">
          Imported from PDF: <strong>{spec.pdfIngestHints.templateLabel}</strong>.
          {spec.pdfIngestHints.roundsBuilt ? (
            <>
              {" "}
              <strong>{spec.pdfIngestHints.gamesBuilt ?? 11} games</strong> were built from PDF routing
              {spec.pdfIngestHints.scheduleLinesApplied
                ? ` (${spec.pdfIngestHints.scheduleLinesApplied} with schedule lines)`
                : ""}
              . Replace placeholder teams (A–
              {spec.pdfIngestHints.teamCount
                ? String.fromCharCode(64 + spec.pdfIngestHints.teamCount)
                : "?"}
              ) via Team name mapping or the Teams step — you can skip the wizard to use the live preview.
            </>
          ) : (
            <>
              {" "}
              Placeholder teams (A–
              {spec.pdfIngestHints.teamCount
                ? String.fromCharCode(64 + spec.pdfIngestHints.teamCount)
                : "?"}
              ) are pre-filled — replace them with real league names on the Teams step.
            </>
          )}
        </p>
      ) : null}

      <ol className="mt-3 flex flex-wrap gap-2 text-[11px] text-zinc-500">
        <li className={step === "format" ? "text-violet-300" : ""}>1. Template</li>
        {setupMode === "official" || bracketFormat === "single_elimination" || isDoubleEliminationFormat(bracketFormat) ? (
          <>
            <li className={step === "division" ? "text-violet-300" : ""}>2. Division</li>
            <li className={step === "champion" ? "text-violet-300" : ""}>3. Champion</li>
            <li className={step === "teams" ? "text-violet-300" : ""}>4. Teams</li>
            {byeCount > 0 ? <li className={step === "byes" ? "text-violet-300" : ""}>5. Byes</li> : null}
            <li className={step === "confirm" ? "text-violet-300" : ""}>
              {byeCount > 0 ? "6" : "5"}. Confirm &amp; build
            </li>
          </>
        ) : (
          <li className={step === "non_single_done" ? "text-violet-300" : ""}>2. Confirm &amp; build</li>
        )}
      </ol>

      {step === "format" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm text-zinc-300">Choose an official tournament template or a custom format.</p>
          <label className="block text-xs font-medium text-zinc-500">
            Setup mode
            <select
              className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm"
              value={setupMode}
              disabled={busy}
              onChange={(e) => {
                const mode = e.target.value as SetupMode;
                setSetupMode(mode);
                if (mode === "official") {
                  const tmpl = getOfficialTemplate(officialTemplateId) ?? defaultTemplate;
                  setChampionshipSeriesStyle(tmpl.defaultChampionshipSeriesStyle);
                  setBracketFormat(bracketFormatForChampionshipSeriesStyle(tmpl.defaultChampionshipSeriesStyle));
                }
              }}
            >
              <option value="official">Official tournament-legal template (recommended)</option>
              <option value="custom">Custom bracket format</option>
            </select>
          </label>
          {setupMode === "official" ? (
            <>
              <div>
                <p className="text-xs font-medium text-zinc-500">Little League template</p>
                <div className="mt-2 grid gap-2 sm:grid-cols-2">
                  {officialTemplateOptions.map((tmpl) => {
                    const selected = tmpl.id === officialTemplateId;
                    return (
                      <button
                        key={tmpl.id}
                        type="button"
                        disabled={busy}
                        className={`rounded-lg border p-3 text-left text-sm transition ${
                          selected
                            ? "border-violet-500 bg-violet-950/50 text-violet-100"
                            : "border-zinc-700 bg-zinc-950 text-zinc-300 hover:border-zinc-500"
                        } disabled:opacity-40`}
                        onClick={() => {
                          const id = tmpl.id as OfficialTemplateId;
                          setOfficialTemplateId(id);
                          setChampionshipSeriesStyle(tmpl.defaultChampionshipSeriesStyle);
                          setBracketFormat(bracketFormatForChampionshipSeriesStyle(tmpl.defaultChampionshipSeriesStyle));
                          if (teams.length === 0 || teams.every((x) => /^[A-Z]$/.test(x))) {
                            setTeams(Array.from({ length: tmpl.teamCount }, (_, i) => String.fromCharCode(65 + i)));
                          }
                        }}
                      >
                        <span className="block font-semibold">{tmpl.teamCount}-team official DE</span>
                        <span className="mt-1 block text-xs text-zinc-500">
                          {tmpl.defaultChampionshipSeriesStyle === "winner_take_all"
                            ? "Defaults to modified, winner-take-all final"
                            : "Defaults to standard, if-necessary final"}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>
              <label className="block text-xs font-medium text-zinc-500">
                Championship series
                <select
                  className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm"
                  value={championshipSeriesStyle}
                  disabled={busy}
                  onChange={(e) => {
                    const style = e.target.value as ChampionshipSeriesStyle;
                    setChampionshipSeriesStyle(style);
                    setBracketFormat(bracketFormatForChampionshipSeriesStyle(style));
                  }}
                >
                  <option value="winner_take_all">Modified — winner-take-all final (no if-necessary game)</option>
                  <option value="always_scheduled_reset">Standard — grand final + if-necessary game</option>
                </select>
              </label>
              <p className="text-xs text-zinc-500">{officialTemplateChampionshipLabel(championshipSeriesStyle)}</p>
            </>
          ) : (
            <select
              className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm"
              value={bracketFormat}
              disabled={busy}
              onChange={(e) => setBracketFormat(e.target.value as BracketFormat)}
            >
              <option value="single_elimination">Single elimination</option>
              <option value="double_elimination">Double elimination</option>
              <option value="modified_double_elimination">Modified double elimination</option>
              <option value="pool_play">Pool play</option>
              <option value="custom">Custom</option>
              <option value="unknown">Unknown / not set</option>
            </select>
          )}
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-600 disabled:opacity-40"
              onClick={() => goNextFromFormat()}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}

      {step === "division" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm text-zinc-300">Optional division or bracket title (shown above the bracket).</p>
          <input
            className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"
            value={divisionLabel}
            disabled={busy}
            onChange={(e) => setDivisionLabel(e.target.value)}
            placeholder="e.g. 12U Majors"
          />
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep("format")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy}
              className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-600"
              onClick={() => setStep("champion")}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}

      {step === "champion" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm text-zinc-300">
            Optional <strong className="font-medium text-zinc-200">champion banner</strong>
            {bracketFormat === "single_elimination" ? (
              <>
                {" "}
                and <strong className="font-medium text-zinc-200">third-place game</strong> (single elimination with
                two semifinals only).
              </>
            ) : (
              <> for the championship series.</>
            )}
          </p>
          <label className="block text-xs font-medium text-zinc-500">
            Champion heading uses this age group or label (e.g. <span className="font-mono text-zinc-400">12U</span>).
            Leave blank to reuse the division title when set.
            <input
              className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"
              value={championAgeGroupDraft}
              disabled={busy}
              onChange={(e) => setChampionAgeGroupDraft(e.target.value)}
              placeholder={divisionLabel.trim() || "e.g. 12U"}
            />
          </label>
          <label className="flex cursor-pointer items-start gap-2 text-sm text-zinc-300">
            <input
              type="checkbox"
              className="mt-1"
              checked={includeThirdPlaceDraft}
              disabled={busy || bracketFormat !== "single_elimination"}
              onChange={(e) => setIncludeThirdPlaceDraft(e.target.checked)}
            />
            <span>
              Include a <strong className="font-medium text-zinc-200">3rd place</strong> game between the two semifinal
              losers (single elimination only).
            </span>
          </label>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep("division")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy}
              className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-600"
              onClick={() => {
                if (!rosterAgeGroupDraft.trim() && championAgeGroupDraft.trim()) {
                  setRosterAgeGroupDraft(championAgeGroupDraft.trim());
                }
                setStep("teams");
              }}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}

      {step === "teams" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm text-zinc-300">
            Select teams from the league roster for this age group, or type names in seed order below (best seed
            first).
          </p>
          <BracketTeamPicker
            organizationId={organizationId}
            seasonYear={seasonYear}
            busy={busy}
            selectedTeamNames={teams}
            onSelectedTeamNamesChange={setTeams}
            rosterAgeGroup={rosterAgeGroupDraft}
            championAgeGroupLabel={championAgeGroupDraft}
            divisionLabel={divisionLabel}
            onAgeGroupChange={(ag) => {
              setRosterAgeGroupDraft(ag);
              if (ag.trim() && !championAgeGroupDraft.trim()) {
                setChampionAgeGroupDraft(ag.trim());
              }
            }}
          />
          {!canBuild && teams.length >= 1 ? (
            <p className="text-xs text-amber-300">
              This list cannot be auto-built (need 2–32 teams so the padded bracket fits in 32 slots). Trim the list or
              skip the questionnaire and define rounds by hand.
            </p>
          ) : null}
          {teams.length < 1 ? <p className="text-xs text-zinc-500">Add at least one team to continue.</p> : null}
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep("champion")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy || teams.length < 1 || !canBuild}
              className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-600 disabled:opacity-40"
              onClick={() => goNextFromTeams()}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}

      {step === "byes" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm text-zinc-300">
            You have <strong className="text-zinc-100">{teams.length}</strong> teams. The next power-of-two field size
            is <strong className="text-zinc-100">{slotN}</strong>, so{" "}
            <strong className="text-zinc-100">{byeCount}</strong> first-round{" "}
            {byeCount === 1 ? "slot is" : "slots are"} filled with <strong className="text-zinc-100">{BYE_SLOT_LABEL}</strong>
            .
          </p>
          <p className="text-xs text-zinc-500">
            Trailing empty slots are assigned {BYE_SLOT_LABEL} after your list; the standard bracket shell pairs them so
            higher seeds (lines closer to the top) receive first-round byes when the shell allows.
          </p>
          <label className="flex cursor-pointer items-start gap-2 text-sm text-zinc-300">
            <input
              type="checkbox"
              className="mt-1"
              checked={byeAck}
              disabled={busy}
              onChange={(e) => setByeAck(e.target.checked)}
            />
            <span>I understand how automatic byes are placed.</span>
          </label>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep("teams")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy || (byeCount > 0 && !byeAck)}
              className="rounded-lg bg-violet-700 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-600 disabled:opacity-40"
              onClick={() => goNextFromByes()}
            >
              Next
            </button>
          </div>
        </div>
      ) : null}

      {step === "confirm" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm font-medium text-zinc-200">Confirm your answers</p>
          <p className="text-xs text-zinc-500">Final step: verify everything below, then build the bracket.</p>
          <ul className="list-inside list-disc text-xs text-zinc-400">
            <li>
              Template:{" "}
              {activeOfficialTemplate
                ? activeOfficialTemplate.label
                : bracketFormat === "modified_double_elimination"
                  ? "modified double elimination"
                  : bracketFormat === "double_elimination"
                    ? "double elimination"
                    : "single elimination"}
            </li>
            {setupMode === "official" || isDoubleEliminationFormat(bracketFormat) ? (
              <li>Championship: {officialTemplateChampionshipLabel(championshipSeriesStyle)}</li>
            ) : null}
            {divisionLabel.trim() ? <li>Title: {divisionLabel.trim()}</li> : <li>Title: (none)</li>}
            <li>
              Champion label:{" "}
              {championAgeGroupDraft.trim()
                ? championAgeGroupDraft.trim()
                : divisionLabel.trim()
                  ? `(use division title: ${divisionLabel.trim()})`
                  : "(default: Tournament)"}
            </li>
            {bracketFormat === "single_elimination" ? (
              <li>3rd place game: {includeThirdPlaceDraft ? "yes" : "no"}</li>
            ) : null}
            {rosterAgeGroupDraft.trim() ? <li>Roster age group: {rosterAgeGroupDraft.trim()}</li> : null}
            <li>
              Teams: {teams.length} ({slotN}-slot bracket{byeCount > 0 ? `, ${byeCount} BYE${byeCount === 1 ? "" : "s"}` : ""})
            </li>
            {isDoubleEliminationFormat(bracketFormat) && slotN >= 2 ? (
              <li>
                Games:{" "}
                {championshipSeriesStyle === "winner_take_all"
                  ? `${countDoubleElimGamesMin(slotN)} (winner-take-all championship)`
                  : `${countDoubleElimGamesMin(slotN)}–${countDoubleElimGamesMax(slotN)} (including if-necessary)`}
              </li>
            ) : null}
          </ul>
          <div className="rounded-lg border border-zinc-700 bg-zinc-950/50 p-2">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-500">Seeded list</p>
            <pre className="mt-1 max-h-32 overflow-auto whitespace-pre-wrap font-mono text-[11px] text-zinc-300">
              {teamsText.trim() || "(none)"}
            </pre>
          </div>
          {previewRounds ? (
            <div className="rounded-lg border border-zinc-700 bg-zinc-950/50 p-2">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-zinc-500">
                {isDoubleEliminationFormat(bracketFormat) ? "Winners round 1 (preview)" : "Round 1 (preview)"}
              </p>
              <ul className="mt-1 space-y-1 font-mono text-[11px] text-zinc-300">
                {(isDoubleEliminationFormat(bracketFormat)
                  ? previewRounds.find((r) => r.bracketSection === "winners")
                  : previewRounds[0]
                )?.matches.map((m) => (
                  <li key={m.id}>
                    {m.home} vs {m.away}
                  </li>
                ))}
              </ul>
            </div>
          ) : (
            <p className="text-xs text-red-400">Could not build preview.</p>
          )}
          <p className="text-xs text-amber-200/90">
            This replaces the project&apos;s <strong className="font-medium">teams</strong> and{" "}
            <strong className="font-medium">rounds</strong> with the generated bracket and unlocks Bracket structure and
            Preview.
          </p>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep(byeCount > 0 ? "byes" : "teams")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy || !previewRounds}
              className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white hover:bg-emerald-600 disabled:opacity-40"
              onClick={() =>
                void (
                  setupMode === "official" || isDoubleEliminationFormat(bracketFormat)
                    ? applyDoubleElimBuild()
                    : applySingleElim()
                )
              }
            >
              Build bracket
            </button>
          </div>
        </div>
      ) : null}

      {step === "non_single_done" ? (
        <div className="mt-4 space-y-3">
          <p className="text-sm font-medium text-zinc-200">Confirm</p>
          <p className="text-xs text-zinc-500">
            For non–single-elimination formats, rounds are defined in Bracket structure after you continue.
          </p>
          <ul className="list-inside list-disc text-xs text-zinc-400">
            <li>Format: {bracketFormat.replace(/_/g, " ")}</li>
            {divisionLabel.trim() ? <li>Title: {divisionLabel.trim()}</li> : <li>Title: (none)</li>}
          </ul>
          <input
            className="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"
            value={divisionLabel}
            disabled={busy}
            onChange={(e) => setDivisionLabel(e.target.value)}
            placeholder="Optional division title"
          />
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy}
              className="rounded-lg border border-zinc-600 px-3 py-2 text-xs hover:bg-zinc-800"
              onClick={() => setStep("format")}
            >
              Back
            </button>
            <button
              type="button"
              disabled={busy}
              className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white hover:bg-emerald-600"
              onClick={() => void applyNonSingle()}
            >
              Build bracket
            </button>
          </div>
        </div>
      ) : null}

      {!setupComplete ? (
        <div className="mt-6 border-t border-zinc-800 pt-4">
          <button
            type="button"
            disabled={busy}
            className="text-xs text-zinc-500 underline decoration-zinc-600 underline-offset-2 hover:text-zinc-300"
            onClick={() => void onSkipGuidedSetup()}
          >
            Skip questionnaire — unlock Bracket structure and Preview without guided answers
          </button>
        </div>
      ) : null}
    </div>
  );
}
